
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace GameConfig
{
public partial class Tables
{
    #region The Tables

    private Main.TbChAttrConfig m_TbChAttrConfig;
    public Main.TbChAttrConfig TbChAttrConfig 
    {
        get
        {
            if (m_TbChAttrConfig == null)
            {
                m_TbChAttrConfig = new Main.TbChAttrConfig(defaultLoader("main_tbchattrconfig"));
                m_TbChAttrConfig.ResolveRef(this);
            }
            return m_TbChAttrConfig;
        }
        set
        {
            m_TbChAttrConfig = value;
            m_TbChAttrConfig.ResolveRef(this);
        }
    }
    /// <summary>
    /// 角色招式Hit配置表
    /// </summary>
    private Main.TbChHitConfig m_TbChHitConfig;
    public Main.TbChHitConfig TbChHitConfig 
    {
        get
        {
            if (m_TbChHitConfig == null)
            {
                m_TbChHitConfig = new Main.TbChHitConfig(defaultLoader("main_tbchhitconfig"));
                m_TbChHitConfig.ResolveRef(this);
            }
            return m_TbChHitConfig;
        }
        set
        {
            m_TbChHitConfig = value;
            m_TbChHitConfig.ResolveRef(this);
        }
    }
    private Main.TbChMotionConfig m_TbChMotionConfig;
    public Main.TbChMotionConfig TbChMotionConfig 
    {
        get
        {
            if (m_TbChMotionConfig == null)
            {
                m_TbChMotionConfig = new Main.TbChMotionConfig(defaultLoader("main_tbchmotionconfig"));
                m_TbChMotionConfig.ResolveRef(this);
            }
            return m_TbChMotionConfig;
        }
        set
        {
            m_TbChMotionConfig = value;
            m_TbChMotionConfig.ResolveRef(this);
        }
    }
    /// <summary>
    /// 角色招式消耗配置表
    /// </summary>
    private Main.TbChActionConfig m_TbChActionConfig;
    public Main.TbChActionConfig TbChActionConfig 
    {
        get
        {
            if (m_TbChActionConfig == null)
            {
                m_TbChActionConfig = new Main.TbChActionConfig(defaultLoader("main_tbchactionconfig"));
                m_TbChActionConfig.ResolveRef(this);
            }
            return m_TbChActionConfig;
        }
        set
        {
            m_TbChActionConfig = value;
            m_TbChActionConfig.ResolveRef(this);
        }
    }
    private Main.TbWeaponConfig m_TbWeaponConfig;
    public Main.TbWeaponConfig TbWeaponConfig 
    {
        get
        {
            if (m_TbWeaponConfig == null)
            {
                m_TbWeaponConfig = new Main.TbWeaponConfig(defaultLoader("main_tbweaponconfig"));
                m_TbWeaponConfig.ResolveRef(this);
            }
            return m_TbWeaponConfig;
        }
        set
        {
            m_TbWeaponConfig = value;
            m_TbWeaponConfig.ResolveRef(this);
        }
    }
    private Main.TbNPCConfig m_TbNPCConfig;
    public Main.TbNPCConfig TbNPCConfig 
    {
        get
        {
            if (m_TbNPCConfig == null)
            {
                m_TbNPCConfig = new Main.TbNPCConfig(defaultLoader("main_tbnpcconfig"));
                m_TbNPCConfig.ResolveRef(this);
            }
            return m_TbNPCConfig;
        }
        set
        {
            m_TbNPCConfig = value;
            m_TbNPCConfig.ResolveRef(this);
        }
    }
    private Main.TbDialogueGraphSentenceConfig m_TbDialogueGraphSentenceConfig;
    public Main.TbDialogueGraphSentenceConfig TbDialogueGraphSentenceConfig 
    {
        get
        {
            if (m_TbDialogueGraphSentenceConfig == null)
            {
                m_TbDialogueGraphSentenceConfig = new Main.TbDialogueGraphSentenceConfig(defaultLoader("main_tbdialoguegraphsentenceconfig"));
                m_TbDialogueGraphSentenceConfig.ResolveRef(this);
            }
            return m_TbDialogueGraphSentenceConfig;
        }
        set
        {
            m_TbDialogueGraphSentenceConfig = value;
            m_TbDialogueGraphSentenceConfig.ResolveRef(this);
        }
    }
    private Main.TbDialogueGraphOptionConfig m_TbDialogueGraphOptionConfig;
    public Main.TbDialogueGraphOptionConfig TbDialogueGraphOptionConfig 
    {
        get
        {
            if (m_TbDialogueGraphOptionConfig == null)
            {
                m_TbDialogueGraphOptionConfig = new Main.TbDialogueGraphOptionConfig(defaultLoader("main_tbdialoguegraphoptionconfig"));
                m_TbDialogueGraphOptionConfig.ResolveRef(this);
            }
            return m_TbDialogueGraphOptionConfig;
        }
        set
        {
            m_TbDialogueGraphOptionConfig = value;
            m_TbDialogueGraphOptionConfig.ResolveRef(this);
        }
    }
    private Main.TbQuestChainConfig m_TbQuestChainConfig;
    public Main.TbQuestChainConfig TbQuestChainConfig 
    {
        get
        {
            if (m_TbQuestChainConfig == null)
            {
                m_TbQuestChainConfig = new Main.TbQuestChainConfig(defaultLoader("main_tbquestchainconfig"));
                m_TbQuestChainConfig.ResolveRef(this);
            }
            return m_TbQuestChainConfig;
        }
        set
        {
            m_TbQuestChainConfig = value;
            m_TbQuestChainConfig.ResolveRef(this);
        }
    }
    private Main.TbDisplayConfig m_TbDisplayConfig;
    public Main.TbDisplayConfig TbDisplayConfig 
    {
        get
        {
            if (m_TbDisplayConfig == null)
            {
                m_TbDisplayConfig = new Main.TbDisplayConfig(defaultLoader("main_tbdisplayconfig"));
                m_TbDisplayConfig.ResolveRef(this);
            }
            return m_TbDisplayConfig;
        }
        set
        {
            m_TbDisplayConfig = value;
            m_TbDisplayConfig.ResolveRef(this);
        }
    }
    private Main.TbAudioConfig m_TbAudioConfig;
    public Main.TbAudioConfig TbAudioConfig 
    {
        get
        {
            if (m_TbAudioConfig == null)
            {
                m_TbAudioConfig = new Main.TbAudioConfig(defaultLoader("main_tbaudioconfig"));
                m_TbAudioConfig.ResolveRef(this);
            }
            return m_TbAudioConfig;
        }
        set
        {
            m_TbAudioConfig = value;
            m_TbAudioConfig.ResolveRef(this);
        }
    }
    private Main.TbControlsConfig m_TbControlsConfig;
    public Main.TbControlsConfig TbControlsConfig 
    {
        get
        {
            if (m_TbControlsConfig == null)
            {
                m_TbControlsConfig = new Main.TbControlsConfig(defaultLoader("main_tbcontrolsconfig"));
                m_TbControlsConfig.ResolveRef(this);
            }
            return m_TbControlsConfig;
        }
        set
        {
            m_TbControlsConfig = value;
            m_TbControlsConfig.ResolveRef(this);
        }
    }
    private Main.TbSystemConfig m_TbSystemConfig;
    public Main.TbSystemConfig TbSystemConfig 
    {
        get
        {
            if (m_TbSystemConfig == null)
            {
                m_TbSystemConfig = new Main.TbSystemConfig(defaultLoader("main_tbsystemconfig"));
                m_TbSystemConfig.ResolveRef(this);
            }
            return m_TbSystemConfig;
        }
        set
        {
            m_TbSystemConfig = value;
            m_TbSystemConfig.ResolveRef(this);
        }
    }

    #endregion

    System.Func<string, ByteBuf> defaultLoader;

    public Tables(System.Func<string, ByteBuf> loader)
    {
        SetDefaultLoader(loader);
        Init();
    }
    
    public void SetDefaultLoader(System.Func<string, ByteBuf> loader)
    {
        defaultLoader = null;
        defaultLoader = loader;
    }

    //public partial void Init();

    public void Init(){}
}

}
