
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Main
{
/// <summary>
/// 属性
/// </summary>
public sealed partial class Attrubute : Luban.BeanBase
{
    public Attrubute(ByteBuf _buf) 
    {
        AttrType = _buf.ReadInt();
        Value = _buf.ReadFloat();
    }

    public static Attrubute DeserializeAttrubute(ByteBuf _buf)
    {
        return new Main.Attrubute(_buf);
    }

    /// <summary>
    /// 属性类型
    /// </summary>
    public readonly int AttrType;
    /// <summary>
    /// 属性值
    /// </summary>
    public readonly float Value;
   
    public const int __ID__ = -812517709;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "attrType:" + AttrType + ","
        + "value:" + Value + ","
        + "}";
    }
}
}

