
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Main
{
public sealed partial class AudioConfig : Luban.BeanBase
{
    public AudioConfig(ByteBuf _buf) 
    {
        Key = _buf.ReadString();
        Content = global::GameConfig.Main.UIContentConfig.DeserializeUIContentConfig(_buf);
    }

    public static AudioConfig DeserializeAudioConfig(ByteBuf _buf)
    {
        return new Main.AudioConfig(_buf);
    }

    /// <summary>
    /// 配置Key
    /// </summary>
    public readonly string Key;
    public readonly Main.UIContentConfig Content;
   
    public const int __ID__ = -916181501;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Content?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "key:" + Key + ","
        + "content:" + Content + ","
        + "}";
    }
}
}

