
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Main
{
public sealed partial class ChActionConfig : Luban.BeanBase
{
    public ChActionConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        ActionType = (Main.EActionType)_buf.ReadInt();
        BuffTags = (Main.EActionBuffTag)_buf.ReadInt();
        EnergyCost = _buf.ReadFloat();
        ChainGaugeCost = _buf.ReadFloat();
        DodgeStaminaCost = _buf.ReadFloat();
        Priority = _buf.ReadInt();
        Comment = _buf.ReadString();
        DecibelCost = _buf.ReadFloat();
    }

    public static ChActionConfig DeserializeChActionConfig(ByteBuf _buf)
    {
        return new Main.ChActionConfig(_buf);
    }

    /// <summary>
    /// ActionId
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 招式名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 动作类型
    /// </summary>
    public readonly Main.EActionType ActionType;
    /// <summary>
    /// 攻击类型
    /// </summary>
    public readonly Main.EActionBuffTag BuffTags;
    /// <summary>
    /// 能量消耗
    /// </summary>
    public readonly float EnergyCost;
    /// <summary>
    /// 连携槽消耗
    /// </summary>
    public readonly float ChainGaugeCost;
    /// <summary>
    /// 闪避体力消耗
    /// </summary>
    public readonly float DodgeStaminaCost;
    /// <summary>
    /// 优先级
    /// </summary>
    public readonly int Priority;
    /// <summary>
    /// 注释
    /// </summary>
    public readonly string Comment;
    /// <summary>
    /// 喧响值消耗（Todo：目前程序默认清空，防止后面有调整因此保留。）
    /// </summary>
    public readonly float DecibelCost;
   
    public const int __ID__ = -911459598;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "actionType:" + ActionType + ","
        + "buffTags:" + BuffTags + ","
        + "energyCost:" + EnergyCost + ","
        + "chainGaugeCost:" + ChainGaugeCost + ","
        + "dodgeStaminaCost:" + DodgeStaminaCost + ","
        + "priority:" + Priority + ","
        + "comment:" + Comment + ","
        + "decibelCost:" + DecibelCost + ","
        + "}";
    }
}
}

