
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Main
{
public sealed partial class ChAttrConfig : Luban.BeanBase
{
    public ChAttrConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); BaseAttr = new System.Collections.Generic.List<Main.Attrubute>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { Main.Attrubute _e0;  _e0 = global::GameConfig.Main.Attrubute.DeserializeAttrubute(_buf); BaseAttr.Add(_e0);}}
    }

    public static ChAttrConfig DeserializeChAttrConfig(ByteBuf _buf)
    {
        return new Main.ChAttrConfig(_buf);
    }

    /// <summary>
    /// 角色Id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 基础属性
    /// </summary>
    public readonly System.Collections.Generic.List<Main.Attrubute> BaseAttr;
   
    public const int __ID__ = 1316310253;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in BaseAttr) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "baseAttr:" + Luban.StringUtil.CollectionToString(BaseAttr) + ","
        + "}";
    }
}
}

