
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Main
{
public sealed partial class ChHitConfig : Luban.BeanBase
{
    public ChHitConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        DmgMult = _buf.ReadFloat();
        DazeMult = _buf.ReadFloat();
        Element = _buf.ReadInt();
        Comment = _buf.ReadString();
    }

    public static ChHitConfig DeserializeChHitConfig(ByteBuf _buf)
    {
        return new Main.ChHitConfig(_buf);
    }

    /// <summary>
    /// 招式id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 伤害系数
    /// </summary>
    public readonly float DmgMult;
    /// <summary>
    /// 失衡系数
    /// </summary>
    public readonly float DazeMult;
    /// <summary>
    /// 元素
    /// </summary>
    public readonly int Element;
    /// <summary>
    /// 备注
    /// </summary>
    public readonly string Comment;
   
    public const int __ID__ = 1551227163;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "dmgMult:" + DmgMult + ","
        + "dazeMult:" + DazeMult + ","
        + "element:" + Element + ","
        + "comment:" + Comment + ","
        + "}";
    }
}
}

