
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Main
{
public sealed partial class ChMotionConfig : Luban.BeanBase
{
    public ChMotionConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Id_Ref = null;
        RotationSpeed = _buf.ReadFloat();
        WalkToRunTime = _buf.ReadFloat();
        TurnThreshold = _buf.ReadFloat();
    }

    public static ChMotionConfig DeserializeChMotionConfig(ByteBuf _buf)
    {
        return new Main.ChMotionConfig(_buf);
    }

    /// <summary>
    /// 角色ID
    /// </summary>
    public readonly int Id;
    public Main.ChAttrConfig Id_Ref;
    /// <summary>
    /// 转身速度
    /// </summary>
    public readonly float RotationSpeed;
    /// <summary>
    /// 移动转冲刺时间
    /// </summary>
    public readonly float WalkToRunTime;
    /// <summary>
    /// 转身阈值
    /// </summary>
    public readonly float TurnThreshold;
   
    public const int __ID__ = 548953202;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Id_Ref = tables.TbChAttrConfig.GetOrDefault(Id);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "rotationSpeed:" + RotationSpeed + ","
        + "walkToRunTime:" + WalkToRunTime + ","
        + "turnThreshold:" + TurnThreshold + ","
        + "}";
    }
}
}

