
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Main
{
public sealed partial class ControlConfig : Main.UIContentConfig
{
    public ControlConfig(ByteBuf _buf)  : base(_buf) 
    {
        ActionName = _buf.ReadString();
        LabelTerm = _buf.ReadString();
        EnableKeyboard = _buf.ReadBool();
        EnableMouse = _buf.ReadBool();
    }

    public static ControlConfig DeserializeControlConfig(ByteBuf _buf)
    {
        return new Main.ControlConfig(_buf);
    }

    public readonly string ActionName;
    public readonly string LabelTerm;
    public readonly bool EnableKeyboard;
    public readonly bool EnableMouse;
   
    public const int __ID__ = -1343041654;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "key:" + Key + ","
        + "label:" + Label + ","
        + "order:" + Order + ","
        + "path:" + Path + ","
        + "defaultValue:" + DefaultValue + ","
        + "actionName:" + ActionName + ","
        + "labelTerm:" + LabelTerm + ","
        + "enableKeyboard:" + EnableKeyboard + ","
        + "enableMouse:" + EnableMouse + ","
        + "}";
    }
}
}

