
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Main
{
public sealed partial class DefeatQuestConfig : Main.QuestConfig
{
    public DefeatQuestConfig(ByteBuf _buf)  : base(_buf) 
    {
        Count = _buf.ReadInt();
        MonsterCid = _buf.ReadInt();
    }

    public static DefeatQuestConfig DeserializeDefeatQuestConfig(ByteBuf _buf)
    {
        return new Main.DefeatQuestConfig(_buf);
    }

    public readonly int Count;
    public readonly int MonsterCid;
   
    public const int __ID__ = 2093219484;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "questCid:" + QuestCid + ","
        + "nextQuestCid:" + NextQuestCid + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "npcOverrides:" + Luban.StringUtil.CollectionToString(NpcOverrides) + ","
        + "completeGetQuestChainCid:" + CompleteGetQuestChainCid + ","
        + "trunkNpcCids:" + Luban.StringUtil.CollectionToString(TrunkNpcCids) + ","
        + "count:" + Count + ","
        + "monsterCid:" + MonsterCid + ","
        + "}";
    }
}
}

