
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Main
{
public sealed partial class DialogueQuestConfig : Main.QuestConfig
{
    public DialogueQuestConfig(ByteBuf _buf)  : base(_buf) 
    {
        DialogueCid = _buf.ReadInt();
    }

    public static DialogueQuestConfig DeserializeDialogueQuestConfig(ByteBuf _buf)
    {
        return new Main.DialogueQuestConfig(_buf);
    }

    public readonly int DialogueCid;
   
    public const int __ID__ = 1464593943;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "questCid:" + QuestCid + ","
        + "nextQuestCid:" + NextQuestCid + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "npcOverrides:" + Luban.StringUtil.CollectionToString(NpcOverrides) + ","
        + "completeGetQuestChainCid:" + CompleteGetQuestChainCid + ","
        + "trunkNpcCids:" + Luban.StringUtil.CollectionToString(TrunkNpcCids) + ","
        + "dialogueCid:" + DialogueCid + ","
        + "}";
    }
}
}

