
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Main
{
public sealed partial class DialogueGraphOptionConfig : Luban.BeanBase
{
    public DialogueGraphOptionConfig(ByteBuf _buf) 
    {
        Cid = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); OptionsList = new System.Collections.Generic.List<Main.DialogueOptionsConfig>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { Main.DialogueOptionsConfig _e0;  _e0 = global::GameConfig.Main.DialogueOptionsConfig.DeserializeDialogueOptionsConfig(_buf); OptionsList.Add(_e0);}}
    }

    public static DialogueGraphOptionConfig DeserializeDialogueGraphOptionConfig(ByteBuf _buf)
    {
        return new Main.DialogueGraphOptionConfig(_buf);
    }

    /// <summary>
    /// 对话图ID
    /// </summary>
    public readonly int Cid;
    public readonly System.Collections.Generic.List<Main.DialogueOptionsConfig> OptionsList;
   
    public const int __ID__ = -96294504;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in OptionsList) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "cid:" + Cid + ","
        + "optionsList:" + Luban.StringUtil.CollectionToString(OptionsList) + ","
        + "}";
    }
}
}

