
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Main
{
/// <summary>
/// 对话选项组
/// </summary>
public sealed partial class DialogueOptionsConfig : Luban.BeanBase
{
    public DialogueOptionsConfig(ByteBuf _buf) 
    {
        SubCid = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); Options = new System.Collections.Generic.List<Main.DialogueOptionConfig>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { Main.DialogueOptionConfig _e0;  _e0 = global::GameConfig.Main.DialogueOptionConfig.DeserializeDialogueOptionConfig(_buf); Options.Add(_e0);}}
    }

    public static DialogueOptionsConfig DeserializeDialogueOptionsConfig(ByteBuf _buf)
    {
        return new Main.DialogueOptionsConfig(_buf);
    }

    public readonly int SubCid;
    public readonly System.Collections.Generic.List<Main.DialogueOptionConfig> Options;
   
    public const int __ID__ = -146237933;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in Options) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "subCid:" + SubCid + ","
        + "options:" + Luban.StringUtil.CollectionToString(Options) + ","
        + "}";
    }
}
}

