
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Main
{
/// <summary>
/// 对话句子
/// </summary>
public sealed partial class DialogueSentenceConfig : Luban.BeanBase
{
    public DialogueSentenceConfig(ByteBuf _buf) 
    {
        SubCid = _buf.ReadInt();
        NextSubCid = _buf.ReadInt();
        Name = _buf.ReadString();
        Content = _buf.ReadString();
        ExitCmd = _buf.ReadString();
        Arg1 = _buf.ReadString();
        Arg2 = _buf.ReadString();
        Arg3 = _buf.ReadString();
    }

    public static DialogueSentenceConfig DeserializeDialogueSentenceConfig(ByteBuf _buf)
    {
        return new Main.DialogueSentenceConfig(_buf);
    }

    /// <summary>
    /// 对话条目ID
    /// </summary>
    public readonly int SubCid;
    /// <summary>
    /// 下一个对话条目ID
    /// </summary>
    public readonly int NextSubCid;
    /// <summary>
    /// 说话人名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 对话内容
    /// </summary>
    public readonly string Content;
    /// <summary>
    /// 退出时命令
    /// </summary>
    public readonly string ExitCmd;
    /// <summary>
    /// 命令1
    /// </summary>
    public readonly string Arg1;
    /// <summary>
    /// 命令2
    /// </summary>
    public readonly string Arg2;
    /// <summary>
    /// 命令3
    /// </summary>
    public readonly string Arg3;
   
    public const int __ID__ = 602469202;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "subCid:" + SubCid + ","
        + "nextSubCid:" + NextSubCid + ","
        + "name:" + Name + ","
        + "content:" + Content + ","
        + "exitCmd:" + ExitCmd + ","
        + "arg1:" + Arg1 + ","
        + "arg2:" + Arg2 + ","
        + "arg3:" + Arg3 + ","
        + "}";
    }
}
}

