
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Main
{
public sealed partial class DialogueGraphSentenceConfig : Luban.BeanBase
{
    public DialogueGraphSentenceConfig(ByteBuf _buf) 
    {
        Cid = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); Sentences = new System.Collections.Generic.List<Main.DialogueSentenceConfig>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { Main.DialogueSentenceConfig _e0;  _e0 = global::GameConfig.Main.DialogueSentenceConfig.DeserializeDialogueSentenceConfig(_buf); Sentences.Add(_e0);}}
    }

    public static DialogueGraphSentenceConfig DeserializeDialogueGraphSentenceConfig(ByteBuf _buf)
    {
        return new Main.DialogueGraphSentenceConfig(_buf);
    }

    /// <summary>
    /// 对话图ID
    /// </summary>
    public readonly int Cid;
    public readonly System.Collections.Generic.List<Main.DialogueSentenceConfig> Sentences;
   
    public const int __ID__ = 187166918;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in Sentences) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "cid:" + Cid + ","
        + "sentences:" + Luban.StringUtil.CollectionToString(Sentences) + ","
        + "}";
    }
}
}

