
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Main
{
/// <summary>
/// 对话选项
/// </summary>
public sealed partial class DialogueOptionConfig : Luban.BeanBase
{
    public DialogueOptionConfig(ByteBuf _buf) 
    {
        NextSubCid = _buf.ReadInt();
        Content = _buf.ReadString();
        ClickCmd = _buf.ReadString();
        Arg1 = _buf.ReadString();
        Arg2 = _buf.ReadString();
        Arg3 = _buf.ReadString();
    }

    public static DialogueOptionConfig DeserializeDialogueOptionConfig(ByteBuf _buf)
    {
        return new Main.DialogueOptionConfig(_buf);
    }

    public readonly int NextSubCid;
    public readonly string Content;
    public readonly string ClickCmd;
    public readonly string Arg1;
    public readonly string Arg2;
    public readonly string Arg3;
   
    public const int __ID__ = -1338319068;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "nextSubCid:" + NextSubCid + ","
        + "content:" + Content + ","
        + "clickCmd:" + ClickCmd + ","
        + "arg1:" + Arg1 + ","
        + "arg2:" + Arg2 + ","
        + "arg3:" + Arg3 + ","
        + "}";
    }
}
}

