
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Main
{
public sealed partial class DropdownConfig : Main.UIContentConfig
{
    public DropdownConfig(ByteBuf _buf)  : base(_buf) 
    {
        {int n0 = _buf.ReadSize(); Options = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); Options.Add(_e0);}}
    }

    public static DropdownConfig DeserializeDropdownConfig(ByteBuf _buf)
    {
        return new Main.DropdownConfig(_buf);
    }

    public readonly System.Collections.Generic.List<string> Options;
   
    public const int __ID__ = 1648230280;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "key:" + Key + ","
        + "label:" + Label + ","
        + "order:" + Order + ","
        + "path:" + Path + ","
        + "defaultValue:" + DefaultValue + ","
        + "options:" + Luban.StringUtil.CollectionToString(Options) + ","
        + "}";
    }
}
}

