
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.Main
{ 
    public enum EActionType
    {
        /// <summary>
        /// 无逻辑
        /// </summary>
        None = 0,
        /// <summary>
        /// 无输入时进入待机状态
        /// </summary>
        Idle = 1,
        /// <summary>
        /// 急停/停止移动
        /// </summary>
        Stop = 90,
        /// <summary>
        /// 长时间无输入触发的待机动画
        /// </summary>
        LongIdle = 91,
        /// <summary>
        /// 普通移动
        /// </summary>
        Walk = 100,
        /// <summary>
        /// 冲刺/奔跑状态
        /// </summary>
        Sprint = 101,
        /// <summary>
        /// 检测方向变化后触发转身
        /// </summary>
        TurnBack = 102,
        /// <summary>
        /// 无资源消耗的普通攻击
        /// </summary>
        NormalAttack = 200,
        /// <summary>
        /// 冲刺/前闪后触发的攻击
        /// </summary>
        DashAttack = 201,
        /// <summary>
        /// 长按普攻触发的蓄力攻击
        /// </summary>
        ChargedAttack = 202,
        /// <summary>
        /// 消耗能量的特殊攻击
        /// </summary>
        EnhancedSpecial = 300,
        /// <summary>
        /// 消耗喧响值的大招
        /// </summary>
        Ultimate = 301,
        /// <summary>
        /// 方向键+闪避
        /// </summary>
        DodgeForward = 400,
        /// <summary>
        /// 无方向闪避
        /// </summary>
        DodgeBackward = 401,
        /// <summary>
        /// 极限闪避触发的子弹时间/快速反应
        /// </summary>
        QuickReflect = 402,
        /// <summary>
        /// 弹反远程攻击（如子弹）
        /// </summary>
        ReflectBullet = 403,
        /// <summary>
        /// 主动换人入场攻击
        /// </summary>
        OffensiveSupport = 500,
        /// <summary>
        /// 受击时触发的换人反击
        /// </summary>
        DefensiveSupport = 501,
        /// <summary>
        /// 快速换人（不攻击）
        /// </summary>
        QuickSupport = 502,
        /// <summary>
        /// 精准格挡（消耗连携槽触发支援）
        /// </summary>
        Parry = 600,
        /// <summary>
        /// 失衡后触发的连携攻击
        /// </summary>
        ChainAttack = 601,
    }

} 

