
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.Main
{ 
    [System.Flags]
    public enum EActionBuffTag
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 普通攻击
        /// </summary>
        NormalAttack = 1,
        /// <summary>
        /// 冲刺攻击
        /// </summary>
        DashAttack = 2,
        /// <summary>
        /// 闪避反击
        /// </summary>
        CounterDodge = 4,
        /// <summary>
        /// 支援攻击
        /// </summary>
        SupportAttack = 8,
        /// <summary>
        /// 快速支援
        /// </summary>
        QuickSupport = 16,
        /// <summary>
        /// 强化特殊技
        /// </summary>
        EnhancedSpecial = 32,
        /// <summary>
        /// 终结技
        /// </summary>
        Ultimate = 64,
        /// <summary>
        /// 连携攻击
        /// </summary>
        ChainAttack = 128,
    }

} 

