
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.Main
{ 
    public enum EAttrTpye
    {
        /// <summary>
        /// 攻击力
        /// </summary>
        ATTACK = 100,
        /// <summary>
        /// 基础攻击力
        /// </summary>
        ATTACK_BASE = 101,
        /// <summary>
        /// 额外攻击力
        /// </summary>
        ATTACK_ADD = 102,
        /// <summary>
        /// 百分比攻击力
        /// </summary>
        ATTACK_PER = 103,
        /// <summary>
        /// 防御力
        /// </summary>
        DEFENSE = 200,
        /// <summary>
        /// 基础防御力
        /// </summary>
        DEFENSE_BASE = 201,
        /// <summary>
        /// 额外防御力
        /// </summary>
        DEFENSE_ADD = 202,
        /// <summary>
        /// 百分比防御力
        /// </summary>
        DEFENSE_PER = 203,
        /// <summary>
        /// 生命力
        /// </summary>
        HP = 300,
        /// <summary>
        /// 基础生命力
        /// </summary>
        HP_BASE = 301,
        /// <summary>
        /// 额外生命力
        /// </summary>
        HP_ADD = 302,
        /// <summary>
        /// 百分比生命力
        /// </summary>
        HP_PER = 303,
        /// <summary>
        /// 冲击力
        /// </summary>
        IMPACT = 400,
        /// <summary>
        /// 基础冲击力
        /// </summary>
        IMPACT_BASE = 401,
        /// <summary>
        /// 冲击力
        /// </summary>
        IMPACT_ADD = 402,
        /// <summary>
        /// 百分比冲击力
        /// </summary>
        IMPACT_PER = 403,
        /// <summary>
        /// 异常掌控
        /// </summary>
        ANOMALY_MASTERY = 500,
        /// <summary>
        /// 基础异常掌控
        /// </summary>
        ANOMALY_MASTERY_BASE = 501,
        /// <summary>
        /// 额外异常掌控
        /// </summary>
        ANOMALY_MASTERY_ADD = 502,
        /// <summary>
        /// 百分比异常掌控
        /// </summary>
        ANOMALY_MASTERY_PER = 503,
        /// <summary>
        /// 异常精通
        /// </summary>
        ANOMALY_PROFICIENCY = 600,
        /// <summary>
        /// 基础异常精通
        /// </summary>
        ANOMALY_PROFICIENCY_BASE = 601,
        /// <summary>
        /// 额外异常精通
        /// </summary>
        ANOMALY_PROFICIENCY_ADD = 602,
        /// <summary>
        /// 百分比异常精通
        /// </summary>
        ANOMALY_PROFICIENCY_PER = 603,
        /// <summary>
        /// 能量自动回复
        /// </summary>
        ENERGY_RECHARGE = 700,
        /// <summary>
        /// 基础能量自动回复
        /// </summary>
        ENERGY_RECHARGE_BASE = 701,
        /// <summary>
        /// 额外能量自动回复
        /// </summary>
        ENERGY_RECHARGE_ADD = 702,
        /// <summary>
        /// 百分比能量自动回复
        /// </summary>
        ENERGY_RECHARGE_PER = 703,
        /// <summary>
        /// 暴击率
        /// </summary>
        CRIT_RATE = 800,
        /// <summary>
        /// 暴击伤害
        /// </summary>
        CRIT_DMG = 900,
        /// <summary>
        /// 穿透率
        /// </summary>
        PENETRATION_RATE = 1000,
        /// <summary>
        /// 穿透值
        /// </summary>
        PENETRATION_VALUE = 1100,
        /// <summary>
        /// 增伤
        /// </summary>
        DAMAGE_BONUS = 1200,
        /// <summary>
        /// 能量获得效率
        /// </summary>
        ENERGY_EFFICIENCY = 1300,
        /// <summary>
        /// 造成失衡值提升
        /// </summary>
        DAZE_BONUS = 1400,
        /// <summary>
        /// 当前生命值
        /// </summary>
        CURRENT_HP = 1500,
        /// <summary>
        /// 当前能量值
        /// </summary>
        CURRENT_ENERGY = 1600,
        /// <summary>
        /// 最大能量值
        /// </summary>
        MAX_ENERGY = 1601,
        /// <summary>
        /// 无敌
        /// </summary>
        INVINCIBLE = 1700,
        /// <summary>
        /// 当前失衡值
        /// </summary>
        CURRENT_DAZE = 1800,
        /// <summary>
        /// 最大失衡值
        /// </summary>
        MAX_DAZE = 1900,
        /// <summary>
        /// 失衡时间
        /// </summary>
        DAZE_TIME = 2000,
        /// <summary>
        /// 失衡易伤倍率
        /// </summary>
        DAZE_VULNERABILITY = 2100,
        /// <summary>
        /// 当前闪避槽
        /// </summary>
        CUR_DODGE_STAMINA = 2200,
        /// <summary>
        /// 最大闪避槽
        /// </summary>
        MAX_DODGE_STAMINA = 2201,
        /// <summary>
        /// 当前大招能量
        /// </summary>
        CUR_ULTIMATE_ENERGY = 2300,
        /// <summary>
        /// 最大大招能量
        /// </summary>
        MAX_ULTIMATE_ENERGY = 2301,
        /// <summary>
        /// 当前喧响值
        /// </summary>
        CUR_DECIBELS = 2400,
        /// <summary>
        /// 最大喧响值
        /// </summary>
        MAX_DECIBELS = 2401,
    }

} 

