
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Main
{
public sealed partial class GatherQuestConfig : Main.QuestConfig
{
    public GatherQuestConfig(ByteBuf _buf)  : base(_buf) 
    {
        Count = _buf.ReadInt();
        ItemCid = _buf.ReadInt();
    }

    public static GatherQuestConfig DeserializeGatherQuestConfig(ByteBuf _buf)
    {
        return new Main.GatherQuestConfig(_buf);
    }

    public readonly int Count;
    public readonly int ItemCid;
   
    public const int __ID__ = 582753492;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "questCid:" + QuestCid + ","
        + "nextQuestCid:" + NextQuestCid + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "npcOverrides:" + Luban.StringUtil.CollectionToString(NpcOverrides) + ","
        + "completeGetQuestChainCid:" + CompleteGetQuestChainCid + ","
        + "trunkNpcCids:" + Luban.StringUtil.CollectionToString(TrunkNpcCids) + ","
        + "count:" + Count + ","
        + "itemCid:" + ItemCid + ","
        + "}";
    }
}
}

