
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Main
{
public sealed partial class GotoQuestConfig : Main.QuestConfig
{
    public GotoQuestConfig(ByteBuf _buf)  : base(_buf) 
    {
        Center = ExternalTypeUtil.NewVector3(global::GameConfig.vector3.Deserializevector3(_buf));
        Radius = _buf.ReadFloat();
    }

    public static GotoQuestConfig DeserializeGotoQuestConfig(ByteBuf _buf)
    {
        return new Main.GotoQuestConfig(_buf);
    }

    public readonly UnityEngine.Vector3 Center;
    public readonly float Radius;
   
    public const int __ID__ = 180064044;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "questCid:" + QuestCid + ","
        + "nextQuestCid:" + NextQuestCid + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "npcOverrides:" + Luban.StringUtil.CollectionToString(NpcOverrides) + ","
        + "completeGetQuestChainCid:" + CompleteGetQuestChainCid + ","
        + "trunkNpcCids:" + Luban.StringUtil.CollectionToString(TrunkNpcCids) + ","
        + "center:" + Center + ","
        + "radius:" + Radius + ","
        + "}";
    }
}
}

