
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.Main
{ 
    /// <summary>
    /// 暂未使用
    /// </summary>
    public enum LubanFullScreenMode
    {
        ExclusiveFullScreen = 1,
        FullScreenWindow = 2,
        MaximizedWindow = 3,
        Windowed = 4,
    }

} 

