
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Main
{
public sealed partial class NPCConfig : Luban.BeanBase
{
    public NPCConfig(ByteBuf _buf) 
    {
        NpcId = _buf.ReadInt();
        Name = _buf.ReadString();
        DialogueConfigId = _buf.ReadInt();
    }

    public static NPCConfig DeserializeNPCConfig(ByteBuf _buf)
    {
        return new Main.NPCConfig(_buf);
    }

    /// <summary>
    /// NPC_ID
    /// </summary>
    public readonly int NpcId;
    /// <summary>
    /// NPC名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 对话配置ID
    /// </summary>
    public readonly int DialogueConfigId;
   
    public const int __ID__ = 1254939534;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "npcId:" + NpcId + ","
        + "name:" + Name + ","
        + "dialogueConfigId:" + DialogueConfigId + ","
        + "}";
    }
}
}

