
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Main
{
public sealed partial class NPCOverrideConfig : Luban.BeanBase
{
    public NPCOverrideConfig(ByteBuf _buf) 
    {
        NpcCid = _buf.ReadInt();
        if(_buf.ReadBool()){ Name = _buf.ReadString(); } else { Name = null; }
        DialogueCid = _buf.ReadInt();
    }

    public static NPCOverrideConfig DeserializeNPCOverrideConfig(ByteBuf _buf)
    {
        return new Main.NPCOverrideConfig(_buf);
    }

    public readonly int NpcCid;
    public readonly string Name;
    public readonly int DialogueCid;
   
    public const int __ID__ = 62443130;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "npcCid:" + NpcCid + ","
        + "name:" + Name + ","
        + "dialogueCid:" + DialogueCid + ","
        + "}";
    }
}
}

