
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Main
{
public sealed partial class QuestChainConfig : Luban.BeanBase
{
    public QuestChainConfig(ByteBuf _buf) 
    {
        QuestChainConfigId = _buf.ReadInt();
        Name = _buf.ReadString();
        {int n0 = _buf.ReadSize(); Rewords = new System.Collections.Generic.List<Main.RewordConfig>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { Main.RewordConfig _e0;  _e0 = global::GameConfig.Main.RewordConfig.DeserializeRewordConfig(_buf); Rewords.Add(_e0);}}
        {int n0 = _buf.ReadSize(); Quests = new System.Collections.Generic.List<Main.QuestConfig>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { Main.QuestConfig _e0;  _e0 = global::GameConfig.Main.QuestConfig.DeserializeQuestConfig(_buf); Quests.Add(_e0);}}
    }

    public static QuestChainConfig DeserializeQuestChainConfig(ByteBuf _buf)
    {
        return new Main.QuestChainConfig(_buf);
    }

    /// <summary>
    /// 任务链ID
    /// </summary>
    public readonly int QuestChainConfigId;
    /// <summary>
    /// 任务链名称
    /// </summary>
    public readonly string Name;
    public readonly System.Collections.Generic.List<Main.RewordConfig> Rewords;
    public readonly System.Collections.Generic.List<Main.QuestConfig> Quests;
   
    public const int __ID__ = 1061255862;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in Rewords) { _e?.ResolveRef(tables); }
        foreach (var _e in Quests) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "questChainConfigId:" + QuestChainConfigId + ","
        + "name:" + Name + ","
        + "rewords:" + Luban.StringUtil.CollectionToString(Rewords) + ","
        + "quests:" + Luban.StringUtil.CollectionToString(Quests) + ","
        + "}";
    }
}
}

