
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Main
{
public abstract partial class QuestConfig : Luban.BeanBase
{
    public QuestConfig(ByteBuf _buf) 
    {
        QuestCid = _buf.ReadInt();
        NextQuestCid = _buf.ReadInt();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        {int n0 = _buf.ReadSize(); NpcOverrides = new System.Collections.Generic.List<Main.NPCOverrideConfig>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { Main.NPCOverrideConfig _e0;  _e0 = global::GameConfig.Main.NPCOverrideConfig.DeserializeNPCOverrideConfig(_buf); NpcOverrides.Add(_e0);}}
        CompleteGetQuestChainCid = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); TrunkNpcCids = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); TrunkNpcCids.Add(_e0);}}
    }

    public static QuestConfig DeserializeQuestConfig(ByteBuf _buf)
    {
        switch (_buf.ReadInt())
        {
            case Main.DialogueQuestConfig.__ID__: return new Main.DialogueQuestConfig(_buf);
            case Main.GotoQuestConfig.__ID__: return new Main.GotoQuestConfig(_buf);
            case Main.DefeatQuestConfig.__ID__: return new Main.DefeatQuestConfig(_buf);
            case Main.GatherQuestConfig.__ID__: return new Main.GatherQuestConfig(_buf);
            case Main.UpgradeQuestConfig.__ID__: return new Main.UpgradeQuestConfig(_buf);
            default: throw new SerializationException();
        }
    }

    public readonly int QuestCid;
    public readonly int NextQuestCid;
    public readonly string Name;
    public readonly string Desc;
    public readonly System.Collections.Generic.List<Main.NPCOverrideConfig> NpcOverrides;
    public readonly int CompleteGetQuestChainCid;
    public readonly System.Collections.Generic.List<int> TrunkNpcCids;
   

    public virtual void ResolveRef(Tables tables)
    {
        foreach (var _e in NpcOverrides) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "questCid:" + QuestCid + ","
        + "nextQuestCid:" + NextQuestCid + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "npcOverrides:" + Luban.StringUtil.CollectionToString(NpcOverrides) + ","
        + "completeGetQuestChainCid:" + CompleteGetQuestChainCid + ","
        + "trunkNpcCids:" + Luban.StringUtil.CollectionToString(TrunkNpcCids) + ","
        + "}";
    }
}
}

