
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Main
{
public sealed partial class RewordConfig : Luban.BeanBase
{
    public RewordConfig(ByteBuf _buf) 
    {
        CurrencyCid = _buf.ReadInt();
        Count = _buf.ReadInt();
    }

    public static RewordConfig DeserializeRewordConfig(ByteBuf _buf)
    {
        return new Main.RewordConfig(_buf);
    }

    public readonly int CurrencyCid;
    public readonly int Count;
   
    public const int __ID__ = -251789452;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "currencyCid:" + CurrencyCid + ","
        + "count:" + Count + ","
        + "}";
    }
}
}

