
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Main
{
public sealed partial class SliderConfig : Main.UIContentConfig
{
    public SliderConfig(ByteBuf _buf)  : base(_buf) 
    {
        MinValue = _buf.ReadInt();
        MaxValue = _buf.ReadInt();
    }

    public static SliderConfig DeserializeSliderConfig(ByteBuf _buf)
    {
        return new Main.SliderConfig(_buf);
    }

    public readonly int MinValue;
    public readonly int MaxValue;
   
    public const int __ID__ = -299660904;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "key:" + Key + ","
        + "label:" + Label + ","
        + "order:" + Order + ","
        + "path:" + Path + ","
        + "defaultValue:" + DefaultValue + ","
        + "minValue:" + MinValue + ","
        + "maxValue:" + MaxValue + ","
        + "}";
    }
}
}

