
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Main
{
public partial class TbAudioConfig
{
    private readonly System.Collections.Generic.Dictionary<string, Main.AudioConfig> _dataMap;
    private readonly System.Collections.Generic.List<Main.AudioConfig> _dataList;
    
    public TbAudioConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, Main.AudioConfig>(n);
        _dataList = new System.Collections.Generic.List<Main.AudioConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Main.AudioConfig _v;
            _v = global::GameConfig.Main.AudioConfig.DeserializeAudioConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Key, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, Main.AudioConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Main.AudioConfig> DataList => _dataList;

    public Main.AudioConfig GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Main.AudioConfig Get(string key) => _dataMap[key];
    public Main.AudioConfig this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

