
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Main
{
/// <summary>
/// 角色招式Hit配置表
/// </summary>
public partial class TbChHitConfig
{
    private readonly System.Collections.Generic.Dictionary<int, Main.ChHitConfig> _dataMap;
    private readonly System.Collections.Generic.List<Main.ChHitConfig> _dataList;
    
    public TbChHitConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, Main.ChHitConfig>(n);
        _dataList = new System.Collections.Generic.List<Main.ChHitConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Main.ChHitConfig _v;
            _v = global::GameConfig.Main.ChHitConfig.DeserializeChHitConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, Main.ChHitConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Main.ChHitConfig> DataList => _dataList;

    public Main.ChHitConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Main.ChHitConfig Get(int key) => _dataMap[key];
    public Main.ChHitConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

