
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Main
{
/// <summary>
/// 角色招式消耗配置表
/// </summary>
public partial class TbChActionConfig
{
    private readonly System.Collections.Generic.Dictionary<int, Main.ChActionConfig> _dataMap;
    private readonly System.Collections.Generic.List<Main.ChActionConfig> _dataList;
    
    public TbChActionConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, Main.ChActionConfig>(n);
        _dataList = new System.Collections.Generic.List<Main.ChActionConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Main.ChActionConfig _v;
            _v = global::GameConfig.Main.ChActionConfig.DeserializeChActionConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, Main.ChActionConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Main.ChActionConfig> DataList => _dataList;

    public Main.ChActionConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Main.ChActionConfig Get(int key) => _dataMap[key];
    public Main.ChActionConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

