
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Main
{
public partial class TbChAttrConfig
{
    private readonly System.Collections.Generic.Dictionary<int, Main.ChAttrConfig> _dataMap;
    private readonly System.Collections.Generic.List<Main.ChAttrConfig> _dataList;
    
    public TbChAttrConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, Main.ChAttrConfig>(n);
        _dataList = new System.Collections.Generic.List<Main.ChAttrConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Main.ChAttrConfig _v;
            _v = global::GameConfig.Main.ChAttrConfig.DeserializeChAttrConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, Main.ChAttrConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Main.ChAttrConfig> DataList => _dataList;

    public Main.ChAttrConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Main.ChAttrConfig Get(int key) => _dataMap[key];
    public Main.ChAttrConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

