
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Main
{
public partial class TbChMotionConfig
{
    private readonly System.Collections.Generic.Dictionary<int, Main.ChMotionConfig> _dataMap;
    private readonly System.Collections.Generic.List<Main.ChMotionConfig> _dataList;
    
    public TbChMotionConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, Main.ChMotionConfig>(n);
        _dataList = new System.Collections.Generic.List<Main.ChMotionConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Main.ChMotionConfig _v;
            _v = global::GameConfig.Main.ChMotionConfig.DeserializeChMotionConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, Main.ChMotionConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Main.ChMotionConfig> DataList => _dataList;

    public Main.ChMotionConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Main.ChMotionConfig Get(int key) => _dataMap[key];
    public Main.ChMotionConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

