
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Main
{
public partial class TbControlsConfig
{
    private readonly System.Collections.Generic.Dictionary<string, Main.ControlsConfig> _dataMap;
    private readonly System.Collections.Generic.List<Main.ControlsConfig> _dataList;
    
    public TbControlsConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, Main.ControlsConfig>(n);
        _dataList = new System.Collections.Generic.List<Main.ControlsConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Main.ControlsConfig _v;
            _v = global::GameConfig.Main.ControlsConfig.DeserializeControlsConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Key, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, Main.ControlsConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Main.ControlsConfig> DataList => _dataList;

    public Main.ControlsConfig GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Main.ControlsConfig Get(string key) => _dataMap[key];
    public Main.ControlsConfig this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

