
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Main
{
public partial class TbDialogueGraphSentenceConfig
{
    private readonly System.Collections.Generic.Dictionary<int, Main.DialogueGraphSentenceConfig> _dataMap;
    private readonly System.Collections.Generic.List<Main.DialogueGraphSentenceConfig> _dataList;
    
    public TbDialogueGraphSentenceConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, Main.DialogueGraphSentenceConfig>(n);
        _dataList = new System.Collections.Generic.List<Main.DialogueGraphSentenceConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Main.DialogueGraphSentenceConfig _v;
            _v = global::GameConfig.Main.DialogueGraphSentenceConfig.DeserializeDialogueGraphSentenceConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Cid, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, Main.DialogueGraphSentenceConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Main.DialogueGraphSentenceConfig> DataList => _dataList;

    public Main.DialogueGraphSentenceConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Main.DialogueGraphSentenceConfig Get(int key) => _dataMap[key];
    public Main.DialogueGraphSentenceConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

