
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Main
{
public partial class TbDialogueGraphOptionConfig
{
    private readonly System.Collections.Generic.Dictionary<int, Main.DialogueGraphOptionConfig> _dataMap;
    private readonly System.Collections.Generic.List<Main.DialogueGraphOptionConfig> _dataList;
    
    public TbDialogueGraphOptionConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, Main.DialogueGraphOptionConfig>(n);
        _dataList = new System.Collections.Generic.List<Main.DialogueGraphOptionConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Main.DialogueGraphOptionConfig _v;
            _v = global::GameConfig.Main.DialogueGraphOptionConfig.DeserializeDialogueGraphOptionConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Cid, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, Main.DialogueGraphOptionConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Main.DialogueGraphOptionConfig> DataList => _dataList;

    public Main.DialogueGraphOptionConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Main.DialogueGraphOptionConfig Get(int key) => _dataMap[key];
    public Main.DialogueGraphOptionConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

