
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Main
{
public partial class TbNPCConfig
{
    private readonly System.Collections.Generic.Dictionary<int, Main.NPCConfig> _dataMap;
    private readonly System.Collections.Generic.List<Main.NPCConfig> _dataList;
    
    public TbNPCConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, Main.NPCConfig>(n);
        _dataList = new System.Collections.Generic.List<Main.NPCConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Main.NPCConfig _v;
            _v = global::GameConfig.Main.NPCConfig.DeserializeNPCConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.NpcId, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, Main.NPCConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Main.NPCConfig> DataList => _dataList;

    public Main.NPCConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Main.NPCConfig Get(int key) => _dataMap[key];
    public Main.NPCConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

