
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Main
{
public partial class TbQuestChainConfig
{
    private readonly System.Collections.Generic.Dictionary<int, Main.QuestChainConfig> _dataMap;
    private readonly System.Collections.Generic.List<Main.QuestChainConfig> _dataList;
    
    public TbQuestChainConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, Main.QuestChainConfig>(n);
        _dataList = new System.Collections.Generic.List<Main.QuestChainConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Main.QuestChainConfig _v;
            _v = global::GameConfig.Main.QuestChainConfig.DeserializeQuestChainConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.QuestChainConfigId, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, Main.QuestChainConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Main.QuestChainConfig> DataList => _dataList;

    public Main.QuestChainConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Main.QuestChainConfig Get(int key) => _dataMap[key];
    public Main.QuestChainConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

