
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Main
{
public abstract partial class UIContentConfig : Luban.BeanBase
{
    public UIContentConfig(ByteBuf _buf) 
    {
        Key = _buf.ReadString();
        Label = _buf.ReadString();
        Order = _buf.ReadInt();
        Path = _buf.ReadString();
        DefaultValue = _buf.ReadInt();
    }

    public static UIContentConfig DeserializeUIContentConfig(ByteBuf _buf)
    {
        switch (_buf.ReadInt())
        {
            case Main.DropdownConfig.__ID__: return new Main.DropdownConfig(_buf);
            case Main.SliderConfig.__ID__: return new Main.SliderConfig(_buf);
            case Main.ControlConfig.__ID__: return new Main.ControlConfig(_buf);
            default: throw new SerializationException();
        }
    }

    public readonly string Key;
    public readonly string Label;
    public readonly int Order;
    public readonly string Path;
    public readonly int DefaultValue;
   

    public virtual void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "key:" + Key + ","
        + "label:" + Label + ","
        + "order:" + Order + ","
        + "path:" + Path + ","
        + "defaultValue:" + DefaultValue + ","
        + "}";
    }
}
}

