
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Main
{
public sealed partial class WeaponConfig : Luban.BeanBase
{
    public WeaponConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Rank = _buf.ReadString();
        IconLoc = _buf.ReadString();
        MaxLevelBaseAttrType = _buf.ReadInt();
        MaxLevelBaseAttrValue = _buf.ReadInt();
        MaxLevelAdvancedAttrType = _buf.ReadInt();
        MaxLevelAdvancedAttrValue = _buf.ReadFloat();
        PassiveAbilityName = _buf.ReadString();
        PassiveDesc = _buf.ReadString();
        Desc = _buf.ReadString();
    }

    public static WeaponConfig DeserializeWeaponConfig(ByteBuf _buf)
    {
        return new Main.WeaponConfig(_buf);
    }

    /// <summary>
    /// 装备唯一ID主键
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 装备显示名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 稀有度/品级(C/B/A/S/SSR)
    /// </summary>
    public readonly string Rank;
    /// <summary>
    /// 图标资源路径
    /// </summary>
    public readonly string IconLoc;
    /// <summary>
    /// 满级基础属性类型ID
    /// </summary>
    public readonly int MaxLevelBaseAttrType;
    /// <summary>
    /// 满级基础属性数值
    /// </summary>
    public readonly int MaxLevelBaseAttrValue;
    /// <summary>
    /// 满级高级属性类型ID
    /// </summary>
    public readonly int MaxLevelAdvancedAttrType;
    /// <summary>
    /// 满级高级属性数值(百分比)
    /// </summary>
    public readonly float MaxLevelAdvancedAttrValue;
    /// <summary>
    /// 被动技能代码标识符
    /// </summary>
    public readonly string PassiveAbilityName;
    /// <summary>
    /// 被动技能显示描述
    /// </summary>
    public readonly string PassiveDesc;
    /// <summary>
    /// 装备背景故事/设定说明
    /// </summary>
    public readonly string Desc;
   
    public const int __ID__ = -2033861997;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "rank:" + Rank + ","
        + "iconLoc:" + IconLoc + ","
        + "maxLevelBaseAttrType:" + MaxLevelBaseAttrType + ","
        + "maxLevelBaseAttrValue:" + MaxLevelBaseAttrValue + ","
        + "maxLevelAdvancedAttrType:" + MaxLevelAdvancedAttrType + ","
        + "maxLevelAdvancedAttrValue:" + MaxLevelAdvancedAttrValue + ","
        + "passiveAbilityName:" + PassiveAbilityName + ","
        + "passiveDesc:" + PassiveDesc + ","
        + "desc:" + Desc + ","
        + "}";
    }
}
}

